//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArabaMotor_
    {
        public Nullable<double> Id { get; set; }
        public string MotorAdi { get; set; }
        public Nullable<double> OrjinalBeygir { get; set; }
        public Nullable<double> YeniBeygir { get; set; }
        public Nullable<double> OrjinalTork { get; set; }
        public Nullable<double> YeniTork { get; set; }
        public Nullable<double> YilID { get; set; }
        public Nullable<double> ModelID { get; set; }
        public Nullable<double> YakitTip { get; set; }
        public bool AktifMi { get; set; }
    }
}
