//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArabaYil_
    {
        public int ID { get; set; }
        public string Adi { get; set; }
        public Nullable<double> ModelID { get; set; }
        public bool Aktif { get; set; }
    }
}
