//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bayimusterileri
    {
        public int id { get; set; }
        public string adSoyad { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public string sehir { get; set; }
        public string aracPlaka { get; set; }
        public string aracBilgi { get; set; }
        public Nullable<int> bayiId { get; set; }
    }
}
