//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dosyaTalep
    {
        public int id { get; set; }
        public string aracMarka { get; set; }
        public string aracModel { get; set; }
        public string aracMotor { get; set; }
        public string aracPlaka { get; set; }
        public string stage1 { get; set; }
        public string stage2 { get; set; }
        public string stage3 { get; set; }
        public string dpfDelete { get; set; }
        public string vmaxOff { get; set; }
        public string dtcOff { get; set; }
        public string addblueDelete { get; set; }
        public string hizLimitorDelete { get; set; }
        public string egrDelete { get; set; }
        public string notu { get; set; }
        public string yuklemeTarihi { get; set; }
        public string yuklemeSaati { get; set; }
        public string dosya { get; set; }
        public string durum { get; set; }
        public string bayiAdi { get; set; }
        public string bayiID { get; set; }
        public string modludosya { get; set; }
        public string modTarihi { get; set; }
        public string modSaati { get; set; }
        public string fiyat { get; set; }
    }
}
