//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class hpchiptuningDBEntities2 : DbContext
    {
        public hpchiptuningDBEntities2()
            : base("name=hpchiptuningDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArabaMarka> ArabaMarkas { get; set; }
        public virtual DbSet<ArabaMarkaeski_> ArabaMarkaeski_ { get; set; }
        public virtual DbSet<ArabaModel> ArabaModels { get; set; }
        public virtual DbSet<ArabaModeleski_> ArabaModeleski_ { get; set; }
        public virtual DbSet<ArabaMotor> ArabaMotors { get; set; }
        public virtual DbSet<ArabaMotorEditsiz> ArabaMotorEditsizs { get; set; }
        public virtual DbSet<ArabaMotorSON> ArabaMotorSONs { get; set; }
        public virtual DbSet<ArabaYil> ArabaYils { get; set; }
        public virtual DbSet<ArabaYil_> ArabaYil_ { get; set; }
        public virtual DbSet<BasvuruSayfasi> BasvuruSayfasis { get; set; }
        public virtual DbSet<bayiler> bayilers { get; set; }
        public virtual DbSet<bayimusterileri> bayimusterileris { get; set; }
        public virtual DbSet<benzinchipuygulamasi> benzinchipuygulamasis { get; set; }
        public virtual DbSet<benzinliAraclar> benzinliAraclars { get; set; }
        public virtual DbSet<benzinliuygulamasi> benzinliuygulamasis { get; set; }
        public virtual DbSet<boxuygulamasi> boxuygulamasis { get; set; }
        public virtual DbSet<chiptuning> chiptunings { get; set; }
        public virtual DbSet<chipyazilimiuygulamasi> chipyazilimiuygulamasis { get; set; }
        public virtual DbSet<dizelAraclar> dizelAraclars { get; set; }
        public virtual DbSet<dizeluygulamasi> dizeluygulamasis { get; set; }
        public virtual DbSet<dosyaTalep> dosyaTaleps { get; set; }
        public virtual DbSet<ebulten> ebultens { get; set; }
        public virtual DbSet<ekibimizSayfasi> ekibimizSayfasis { get; set; }
        public virtual DbSet<fotogaleri> fotogaleris { get; set; }
        public virtual DbSet<gelenmesajlar> gelenmesajlars { get; set; }
        public virtual DbSet<gidenmesajlar> gidenmesajlars { get; set; }
        public virtual DbSet<haberlerSayfasi> haberlerSayfasis { get; set; }
        public virtual DbSet<hakkimizdaSayfasi> hakkimizdaSayfasis { get; set; }
        public virtual DbSet<iletisimFormu> iletisimFormus { get; set; }
        public virtual DbSet<iletisimSayfasi> iletisimSayfasis { get; set; }
        public virtual DbSet<iller> illers { get; set; }
        public virtual DbSet<instagramsube> instagramsubes { get; set; }
        public virtual DbSet<mesajlar> mesajlars { get; set; }
        public virtual DbSet<misyonumuzSayfasi> misyonumuzSayfasis { get; set; }
        public virtual DbSet<musteriyorumlari> musteriyorumlaris { get; set; }
        public virtual DbSet<panel> panels { get; set; }
        public virtual DbSet<pedaluygulamasi> pedaluygulamasis { get; set; }
        public virtual DbSet<promosyonlar> promosyonlars { get; set; }
        public virtual DbSet<promosyontalep> promosyontaleps { get; set; }
        public virtual DbSet<raporlar> raporlars { get; set; }
        public virtual DbSet<referanslarSayfasi> referanslarSayfasis { get; set; }
        public virtual DbSet<slider> sliders { get; set; }
        public virtual DbSet<sm> sms { get; set; }
        public virtual DbSet<sorular> sorulars { get; set; }
        public virtual DbSet<sssSayfasi> sssSayfasis { get; set; }
        public virtual DbSet<sssSayfasie> sssSayfasies { get; set; }
        public virtual DbSet<sssSayfasiu> sssSayfasius { get; set; }
        public virtual DbSet<subeler> subelers { get; set; }
        public virtual DbSet<torkvegucartisi> torkvegucartisis { get; set; }
        public virtual DbSet<tumarabaresimler> tumarabaresimlers { get; set; }
        public virtual DbSet<tuningliaraclar> tuningliaraclars { get; set; }
        public virtual DbSet<videogaleri> videogaleris { get; set; }
        public virtual DbSet<vizyonumuzSayfasi> vizyonumuzSayfasis { get; set; }
        public virtual DbSet<y> y { get; set; }
        public virtual DbSet<YagmurArabaMotor> YagmurArabaMotors { get; set; }
        public virtual DbSet<ArabaMotor_> ArabaMotor_ { get; set; }
    
        public virtual ObjectResult<arabamarkamodel_Result> arabamarkamodel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<arabamarkamodel_Result>("arabamarkamodel");
        }
    
        public virtual ObjectResult<arabamm_Result> arabamm()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<arabamm_Result>("arabamm");
        }
    
        public virtual ObjectResult<bayipromosyontalepgor_Result> bayipromosyontalepgor(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bayipromosyontalepgor_Result>("bayipromosyontalepgor", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> fiyattoplam(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("fiyattoplam", idParameter);
        }
    
        public virtual ObjectResult<gonderilenpromosyonlar_Result> gonderilenpromosyonlar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gonderilenpromosyonlar_Result>("gonderilenpromosyonlar");
        }
    
        public virtual ObjectResult<gonderilenpromosyontalepgor_Result> gonderilenpromosyontalepgor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gonderilenpromosyontalepgor_Result>("gonderilenpromosyontalepgor");
        }
    
        public virtual int mesajgonder(string baslik, string icerik, string gonderen, string alici, Nullable<System.DateTime> tarih)
        {
            var baslikParameter = baslik != null ?
                new ObjectParameter("baslik", baslik) :
                new ObjectParameter("baslik", typeof(string));
    
            var icerikParameter = icerik != null ?
                new ObjectParameter("icerik", icerik) :
                new ObjectParameter("icerik", typeof(string));
    
            var gonderenParameter = gonderen != null ?
                new ObjectParameter("gonderen", gonderen) :
                new ObjectParameter("gonderen", typeof(string));
    
            var aliciParameter = alici != null ?
                new ObjectParameter("alici", alici) :
                new ObjectParameter("alici", typeof(string));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("tarih", tarih) :
                new ObjectParameter("tarih", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mesajgonder", baslikParameter, icerikParameter, gonderenParameter, aliciParameter, tarihParameter);
        }
    
        public virtual ObjectResult<musteriyorumgetir_Result> musteriyorumgetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<musteriyorumgetir_Result>("musteriyorumgetir");
        }
    
        public virtual ObjectResult<musteriyorumgetir2_Result> musteriyorumgetir2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<musteriyorumgetir2_Result>("musteriyorumgetir2", idParameter);
        }
    
        public virtual ObjectResult<musteriyorumgetir3_Result> musteriyorumgetir3(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<musteriyorumgetir3_Result>("musteriyorumgetir3", idParameter);
        }
    
        public virtual ObjectResult<promosyontalepgor_Result> promosyontalepgor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<promosyontalepgor_Result>("promosyontalepgor");
        }
    
        public virtual ObjectResult<promosyonuruntipinegoregetir_Result> promosyonuruntipinegoregetir(string tip)
        {
            var tipParameter = tip != null ?
                new ObjectParameter("tip", tip) :
                new ObjectParameter("tip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<promosyonuruntipinegoregetir_Result>("promosyonuruntipinegoregetir", tipParameter);
        }
    
        public virtual ObjectResult<promosyonuruntipinegoregetir2_Result> promosyonuruntipinegoregetir2(string tip)
        {
            var tipParameter = tip != null ?
                new ObjectParameter("tip", tip) :
                new ObjectParameter("tip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<promosyonuruntipinegoregetir2_Result>("promosyonuruntipinegoregetir2", tipParameter);
        }
    }
}
