//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteriyorumlari
    {
        public int id { get; set; }
        public string adSoyad { get; set; }
        public string arac { get; set; }
        public string aracbilgi { get; set; }
        public string tarih { get; set; }
        public string yorum { get; set; }
        public Nullable<int> markaID { get; set; }
        public string resimm { get; set; }
        public string yolu { get; set; }
        public string modelID { get; set; }
        public string durum { get; set; }
    }
}
