//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promosyontalep
    {
        public int id { get; set; }
        public string urunid { get; set; }
        public string adet { get; set; }
        public string durum { get; set; }
        public string taleptarihi { get; set; }
        public string gonderilmetarihi { get; set; }
        public string bayiID { get; set; }
    }
}
