//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promosyonlar
    {
        public int id { get; set; }
        public string urunAd { get; set; }
        public string urunAdet { get; set; }
        public string urunTip { get; set; }
        public string durum { get; set; }
        public string resim { get; set; }
    }
}
