//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slider
    {
        public int id { get; set; }
        public string baslik { get; set; }
        public string yazi { get; set; }
        public string resim1 { get; set; }
        public string resim2 { get; set; }
        public string link { get; set; }
    }
}
