//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subeler
    {
        public int id { get; set; }
        public string subeAdi { get; set; }
        public string yetkiliAdSoyad { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string email { get; set; }
        public string adres { get; set; }
        public string mapkodu { get; set; }
        public string suberesim { get; set; }
        public string suberesimyol { get; set; }
        public string calismaSaat { get; set; }
        public string plakaKodu { get; set; }
    }
}
