//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuningliaraclar
    {
        public int id { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public string orjbeygir { get; set; }
        public string orjtork { get; set; }
        public string kbeygir { get; set; }
        public string ktork { get; set; }
        public string resim { get; set; }
        public string yolu { get; set; }
        public string yakit { get; set; }
    }
}
